### ISSUE TITLE
Upgrade meta file format

### ISSUE THREAD

**Issue by Yshayy** [Soluto/tweek#274]
I believe we have a bit of a problem with the way we organize keys and we need to improve it in order to better support new features and avoid technical debt.

Historaclly, Tweek had support jpad and rules first and meta later, it caused some strong dependency to JPad and weird logic in editor. (for example, for listing keys we look for jpad files and than cross reference it with meta file).

If we look at Tweek from a CI/CD prespective, every key represent an artificat for represting some logic, one way to organize it in a scalable way, is to upgrade our "meta" files to "manifest" file. 

A manifest file will have the following structure:
```
{
      key_path: string,
      meta:{
            name: string,
            tags: string[],
            description: string,
            archived: bool
      },
      implementation: FileImplementation | ConstImplenetation | LinkImplementation,
      valueType: string | CustomType 
      dependencies: string[] //list of depedent keys
      active: bool
}

type FileImplemetation {
        type: "file"
        format: string //for example jpad
}

type ConstImplemetation {
        type: "const"
        value:  any // static value of the key, useful for static configuration like Tweek schema
}

type LinkImplemetation {
        type: "link"
        key: string // redirect for other key, relevant for tweek key linking feature
}
```
These "manifest files" can be indexed by SearchEngine implementation which can provide us a lot of capabilites. other than searching by tags, name. it can be use for key dependencies visualization. 
The validation process can read these files in order to detect circular dependencies.

- [x] Support in editor
- [x] Support in management
- [x] Migration of old keys
- [x] Remove support for old meta format
