### ISSUE TITLE
Persist/save meta key data

### ISSUE THREAD

**Issue by gilm123** [Soluto/tweek#37]
- [x] add meta client
- [x] add new meta repository and mock implementation
- [x] set new couchbase key space
- [x] create couchbase meta repository implementation
- [x] set server api (proxy in serverside to the couchbase)

both client and server should have mock/real meta provider
